const WorkoutsTypes = {
    TOGGLE_WORKOUT_WINDOW: "TOGGLE_NEW_WORKOUT_WINDOW",
    ADD_NEW_WORKOUT: "ADD_NEW_WORKOUT",
    DELETE_WORKOUT: "DELETE_WORKOUT",
    EDIT_WORKOUT: "EDIT_WORKOUT",
    FILTER_BY_DATE: "FILTER_BY_DATE",
    FILTER_BY_TYPE: "FILTER_BY_TYPE"
}

export default WorkoutsTypes;