const WorkoutsTypes = {
    TOGGLE_WORKOUT_WINDOW: "TOGGLE_NEW_WORKOUT_WINDOW",
    ADD_NEW_WORKOUT: "ADD_NEW_WORKOUT",
    DELETE_WORKOUT: "DELETE_WORKOUT",
    EDIT_WORKOUT: "EDIT_WORKOUT",
    FILTER_BY_DATA: "FILTER_BY_DATA",
}

export default WorkoutsTypes;